### ISSUE TITLE
Get Strength Meter

### ISSUE THREAD

**Issue by abhi-cognitivo** [miladd3/vue-simple-password-meter#1]
Hi,

My biggest issues with other password strength packages was the file size. Thankfully I found this one. My only question is, can we somehow get the strength indicator back in the parent control. This way if the score is too low, I can stop the user from saving the form or ask them to improve the password.

**Comment by miladd3** [comment]
Hi
Thank for the idea I will implement an event for this and update the documents for it

**Comment by miladd3** [comment]
Hi again
New `score` Event is added in version 0.17.0 if you update it from npm you can use it.
look at the [readme ](https://github.com/miladd3/vue-simple-password-meter#events) for more detail

**Comment by abhi-cognitivo** [comment]
Your the boss!!
