### ISSUE TITLE
Getting Warning that "score" is not defined in emits

### ISSUE THREAD

**Issue by parkben01** [miladd3/vue-simple-password-meter#3]
I'm getting an error on each keypress (Vue3 @next version) due to the "score" event not being defined in the component. I've been able to silence these warnings by adding this to `password-meter.vue`:

`emits: [
    'score',
],`

Any chance we can get this code in? Thanks!

**Comment by miladd3** [comment]
Hi thank you for the issue,
exactly where you put this code?

**Comment by parkben01** [comment]
You add it into your default export, as a peer to "name", "props", and "computed". like this:

`export default {
  name: 'password-meter',
  props: { ... },
  emits: [
    'score'
   ],
   computed: { ... }
}`

**Comment by miladd3** [comment]
Thank you for your help I added the emit in the newly published version under the @next tag.
can you please see if it's fixed now?

**Comment by parkben01** [comment]
@miladd3 That fixed the warnings! Thanks!
