### ISSUE TITLE
PW 123456789 is considered non-critical

### ISSUE THREAD

**Issue by christianbueschi** [miladd3/vue-simple-password-meter#34]
The password `123456789` is considered as non-critical. Should be critical imo though.

<img width="568" alt="Screenshot 2023-04-03 at 10 07 42" src="https://user-images.githubusercontent.com/5222058/229449833-7e6902a7-3256-4054-ae39-ec3fbab6bd2d.png">

**Comment by miladd3** [comment]
Hi Christian you are right I will see if there is a way to know these common patterns without making the library big.

**Comment by miladd3** [comment]
@christianbueschi 
Updated in both versions (1.3.0(Vue 3) and 0.3.1(Vue 2)) now it will return risky(0) for common passwords 

```js
const commonPasswords = [
  "123456",
  "qwerty",
  "password",
  "111111",
  "Abc123",
  "123456789",
  "12345678",
  "123123",
  "1234567890",
  "12345",
  "1234567",
  "qwertyuiop",
  "qwerty123",
  "1q2w3e",
  "password1",
  "123321",
  "Iloveyou",
  "12345"
]
```
